version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
  web:
    container_name: api
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    links:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db



volumes:
  postgres_data:
